#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'gradingStudents' function below.
#
# The function is expected to return an INTEGER_ARRAY.
# The function accepts INTEGER_ARRAY grades as parameter.
#

def gradingStudents(grades):
  
    rank_after_rounding = []
   
    for value in grades:
        if value >= 38:
            if value % 5 >= 3:
                k = value % 5
                value = value + (5-k)
                rank_after_rounding.append(value)
            else:
                rank_after_rounding.append(value)
        else:
            rank_after_rounding.append(value)
    return rank_after_rounding
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    grades_count = int(input().strip())

    grades = []

    for _ in range(grades_count):
        grades_item = int(input().strip())
        grades.append(grades_item)

    result = gradingStudents(grades)

    fptr.write('\n'.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
